// Magic Search share image generator — renders a WhatsApp-friendly PNG
// summarising a metric/report card via a canvas.

import type { MetricResult, ReportResult } from "./erp-runner";
import type { CompareResult } from "./ai-compare";

const W = 1080;
const H = 1350; // 4:5 — WhatsApp-friendly

function nowStamp() {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

function fmt(n: number) {
  return new Intl.NumberFormat("en", { maximumFractionDigits: 2 }).format(n || 0);
}

function setupCanvas(): { ctx: CanvasRenderingContext2D; canvas: HTMLCanvasElement } {
  const canvas = document.createElement("canvas");
  canvas.width = W; canvas.height = H;
  const ctx = canvas.getContext("2d")!;
  // background
  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, W, H);
  // top accent band
  const grad = ctx.createLinearGradient(0, 0, W, 0);
  grad.addColorStop(0, "#6366f1");
  grad.addColorStop(1, "#22d3ee");
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, W, 12);
  return { ctx, canvas };
}

function drawHeader(ctx: CanvasRenderingContext2D, query: string) {
  ctx.fillStyle = "#0f172a";
  ctx.font = "700 56px system-ui, -apple-system, 'Segoe UI', sans-serif";
  ctx.fillText("Magic Search", 80, 140);

  ctx.fillStyle = "#64748b";
  ctx.font = "500 28px system-ui, -apple-system, 'Segoe UI', sans-serif";
  ctx.fillText("AI ERP Reporting", 80, 188);

  // Query chip
  ctx.fillStyle = "#f1f5f9";
  const qy = 230;
  const padX = 32, padY = 22;
  ctx.font = "500 30px system-ui, -apple-system, 'Segoe UI', sans-serif";
  const tw = Math.min(ctx.measureText(query).width + padX * 2, W - 160);
  roundRect(ctx, 80, qy, tw, 64, 16);
  ctx.fill();
  ctx.fillStyle = "#334155";
  ctx.fillText(truncate(ctx, query, W - 160 - padX * 2), 80 + padX, qy + 64 - padY);
}

function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + w, y, x + w, y + h, r);
  ctx.arcTo(x + w, y + h, x, y + h, r);
  ctx.arcTo(x, y + h, x, y, r);
  ctx.arcTo(x, y, x + w, y, r);
  ctx.closePath();
}

function truncate(ctx: CanvasRenderingContext2D, text: string, maxW: number) {
  if (ctx.measureText(text).width <= maxW) return text;
  let s = text;
  while (s.length > 4 && ctx.measureText(s + "…").width > maxW) s = s.slice(0, -1);
  return s + "…";
}

function drawFooter(ctx: CanvasRenderingContext2D) {
  ctx.fillStyle = "#94a3b8";
  ctx.font = "500 22px system-ui, -apple-system, 'Segoe UI', sans-serif";
  ctx.fillText(`Generated ${nowStamp()}`, 80, H - 130);

  ctx.fillStyle = "#0f172a";
  ctx.font = "700 28px system-ui, -apple-system, 'Segoe UI', sans-serif";
  ctx.fillText("Generated by Manager AhsAN", 80, H - 80);
  ctx.fillStyle = "#64748b";
  ctx.font = "500 24px system-ui, -apple-system, 'Segoe UI', sans-serif";
  ctx.fillText("ShRiAh Group", 80, H - 48);
}

export function renderMetricImage(r: MetricResult, query: string): string {
  const { ctx, canvas } = setupCanvas();
  drawHeader(ctx, query || r.label);

  // Big value card
  const cardY = 340;
  ctx.fillStyle = "#fafafa";
  roundRect(ctx, 80, cardY, W - 160, 380, 28);
  ctx.fill();
  ctx.strokeStyle = "#e2e8f0";
  ctx.lineWidth = 2;
  ctx.stroke();

  ctx.fillStyle = "#64748b";
  ctx.font = "600 26px system-ui, -apple-system, sans-serif";
  ctx.fillText(r.label.toUpperCase(), 120, cardY + 70);

  ctx.fillStyle = "#0f172a";
  ctx.font = "800 110px system-ui, -apple-system, sans-serif";
  ctx.fillText(`SAR ${fmt(r.value)}`, 120, cardY + 200);

  ctx.fillStyle = "#475569";
  ctx.font = "500 26px system-ui, -apple-system, sans-serif";
  ctx.fillText(`Scope: ${r.scopeLabel}`, 120, cardY + 260);
  ctx.fillText(`Date: ${r.dateLabel}`, 120, cardY + 300);
  if (r.intent.cashier) ctx.fillText(`Cashier: ${r.intent.cashier}`, 120, cardY + 340);

  // Breakdown
  if (r.breakdown && r.breakdown.length) {
    let y = cardY + 440;
    ctx.fillStyle = "#0f172a";
    ctx.font = "700 30px system-ui, -apple-system, sans-serif";
    ctx.fillText("Breakdown", 80, y);
    y += 40;
    for (const b of r.breakdown) {
      ctx.fillStyle = "#64748b";
      ctx.font = "500 26px system-ui, -apple-system, sans-serif";
      ctx.fillText(b.label, 100, y);
      ctx.fillStyle = "#0f172a";
      ctx.font = "700 26px system-ui, -apple-system, sans-serif";
      const t = fmt(b.value);
      ctx.fillText(t, W - 80 - ctx.measureText(t).width, y);
      y += 44;
    }
  }

  drawFooter(ctx);
  return canvas.toDataURL("image/png");
}

export function renderReportImage(r: ReportResult, query: string): string {
  const { ctx, canvas } = setupCanvas();
  drawHeader(ctx, query || `${r.scopeLabel} Report`);

  ctx.fillStyle = "#0f172a";
  ctx.font = "700 36px system-ui, -apple-system, sans-serif";
  ctx.fillText(`${r.scopeLabel} Summary`, 80, 360);
  ctx.fillStyle = "#64748b";
  ctx.font = "500 24px system-ui, -apple-system, sans-serif";
  ctx.fillText(r.dateLabel, 80, 396);

  let y = 460;
  for (const row of r.rows) {
    ctx.fillStyle = row.emphasis ? "#0f172a" : "#475569";
    ctx.font = `${row.emphasis ? 700 : 500} 28px system-ui, -apple-system, sans-serif`;
    ctx.fillText(row.label, 100, y);
    const t = fmt(row.value);
    ctx.fillText(t, W - 100 - ctx.measureText(t).width, y);
    if (row.emphasis) {
      ctx.strokeStyle = "#e2e8f0";
      ctx.lineWidth = 1;
      ctx.beginPath(); ctx.moveTo(80, y + 14); ctx.lineTo(W - 80, y + 14); ctx.stroke();
    }
    y += 50;
  }

  drawFooter(ctx);
  return canvas.toDataURL("image/png");
}

export function renderCompareImage(r: CompareResult, query: string): string {
  const { ctx, canvas } = setupCanvas();
  drawHeader(ctx, query || `${r.aLabel} vs ${r.bLabel}`);

  ctx.fillStyle = "#0f172a";
  ctx.font = "700 38px system-ui, -apple-system, sans-serif";
  ctx.fillText(`${r.aLabel}  vs  ${r.bLabel}`, 80, 360);
  ctx.fillStyle = "#64748b";
  ctx.font = "500 24px system-ui, -apple-system, sans-serif";
  ctx.fillText(`${r.kind.toUpperCase()} · ${r.dateLabel}`, 80, 396);

  // Headline
  if (r.winner !== "tie") {
    ctx.fillStyle = "#b45309";
    ctx.font = "700 28px system-ui, -apple-system, sans-serif";
    const lead = r.winner === "a" ? r.aLabel : r.bLabel;
    ctx.fillText(`🏆 ${lead} leads on ${r.headline.label}`, 80, 440);
  }

  // Column headers
  let y = 500;
  ctx.fillStyle = "#64748b";
  ctx.font = "600 22px system-ui, -apple-system, sans-serif";
  ctx.fillText("METRIC", 100, y);
  ctx.textAlign = "right";
  ctx.fillText(r.aLabel.toUpperCase(), 640, y);
  ctx.fillText(r.bLabel.toUpperCase(), W - 100, y);
  ctx.textAlign = "left";
  y += 36;

  for (const row of r.rows) {
    ctx.fillStyle = "#475569";
    ctx.font = "500 26px system-ui, -apple-system, sans-serif";
    ctx.fillText(row.label, 100, y);
    ctx.textAlign = "right";
    ctx.fillStyle = row.a > row.b ? "#059669" : "#0f172a";
    ctx.font = `${row.a > row.b ? 700 : 500} 26px system-ui, -apple-system, sans-serif`;
    ctx.fillText(fmt(row.a), 640, y);
    ctx.fillStyle = row.b > row.a ? "#059669" : "#0f172a";
    ctx.font = `${row.b > row.a ? 700 : 500} 26px system-ui, -apple-system, sans-serif`;
    ctx.fillText(fmt(row.b), W - 100, y);
    ctx.textAlign = "left";
    y += 44;
  }

  drawFooter(ctx);
  return canvas.toDataURL("image/png");
}

export async function shareDataUrl(dataUrl: string, filename: string, caption: string) {
  try {
    const res = await fetch(dataUrl);
    const blob = await res.blob();
    const file = new File([blob], filename, { type: "image/png" });
    const nav: any = navigator;
    if (nav.canShare && nav.canShare({ files: [file] })) {
      await nav.share({ files: [file], title: "Magic Search", text: caption });
      return;
    }
  } catch {
    /* fall through */
  }
  // Fallback: download + open WhatsApp web with caption
  const a = document.createElement("a");
  a.href = dataUrl; a.download = filename;
  document.body.appendChild(a); a.click(); a.remove();
  const wa = `https://wa.me/?text=${encodeURIComponent(caption)}`;
  window.open(wa, "_blank");
}
