// Generates a premium WhatsApp-ready receipt image for an Employee entry.
// Uses an offscreen <canvas> — no extra deps.

type Entry = {
  employeeName: string;
  shopName?: string | null;
  amount: number;
  entryType: "given" | "received";
  date: string;
  notes?: string | null;
  balanceAfter?: number | null;
};

const COMPANY = "ShRiAh Group";

function fmt(n: number) {
  return new Intl.NumberFormat("en", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(n);
}

export async function buildEmployeeShareImage(entry: Entry): Promise<Blob> {
  const W = 1080;
  const H = 1350;
  const canvas = document.createElement("canvas");
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext("2d")!;

  const isGiven = entry.entryType === "given";
  const accent = isGiven ? "#EF4444" : "#10B981";
  const accentSoft = isGiven ? "#FCA5A5" : "#86EFAC";

  // Background gradient
  const bg = ctx.createLinearGradient(0, 0, W, H);
  bg.addColorStop(0, "#0B1220");
  bg.addColorStop(1, "#111B30");
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, W, H);

  // Glow blob
  const glow = ctx.createRadialGradient(W * 0.85, 100, 40, W * 0.85, 100, 600);
  glow.addColorStop(0, accent + "55");
  glow.addColorStop(1, "transparent");
  ctx.fillStyle = glow;
  ctx.fillRect(0, 0, W, H);

  // Receipt card
  const cardX = 70;
  const cardY = 180;
  const cardW = W - 140;
  const cardH = H - 360;
  roundRect(ctx, cardX, cardY, cardW, cardH, 36);
  const cardBg = ctx.createLinearGradient(0, cardY, 0, cardY + cardH);
  cardBg.addColorStop(0, "#15213A");
  cardBg.addColorStop(1, "#0F1A2E");
  ctx.fillStyle = cardBg;
  ctx.fill();
  ctx.strokeStyle = "rgba(255,255,255,0.08)";
  ctx.lineWidth = 2;
  ctx.stroke();

  // Top — brand
  ctx.fillStyle = "#F8FAFC";
  ctx.font = "700 44px Inter, system-ui, sans-serif";
  ctx.textAlign = "left";
  ctx.fillText(COMPANY, 90, 110);

  ctx.fillStyle = "#94A3B8";
  ctx.font = "500 24px Inter, system-ui, sans-serif";
  ctx.fillText("Employee receipt", 90, 145);

  // Type pill
  const pillText = isGiven ? "MONEY GIVEN" : "MONEY RECEIVED";
  ctx.font = "700 22px Inter, system-ui, sans-serif";
  const pillW = ctx.measureText(pillText).width + 44;
  const pillX = W - pillW - 90;
  const pillY = 80;
  roundRect(ctx, pillX, pillY, pillW, 48, 24);
  ctx.fillStyle = accent + "22";
  ctx.fill();
  ctx.strokeStyle = accent + "88";
  ctx.lineWidth = 2;
  ctx.stroke();
  ctx.fillStyle = accent;
  ctx.textAlign = "center";
  ctx.fillText(pillText, pillX + pillW / 2, pillY + 32);

  // Amount
  ctx.textAlign = "center";
  ctx.fillStyle = "#64748B";
  ctx.font = "600 24px Inter, system-ui, sans-serif";
  ctx.fillText("AMOUNT", W / 2, cardY + 90);

  ctx.fillStyle = "#94A3B8";
  ctx.font = "600 32px Inter, system-ui, sans-serif";
  const sarOffsetX = -160;
  ctx.fillText("SAR", W / 2 + sarOffsetX, cardY + 200);

  ctx.fillStyle = "#F8FAFC";
  ctx.font = "800 132px Inter, system-ui, sans-serif";
  ctx.fillText(fmt(entry.amount), W / 2 + 30, cardY + 220);

  // Divider
  ctx.strokeStyle = "rgba(255,255,255,0.08)";
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.setLineDash([8, 8]);
  ctx.moveTo(cardX + 50, cardY + 290);
  ctx.lineTo(cardX + cardW - 50, cardY + 290);
  ctx.stroke();
  ctx.setLineDash([]);

  // Detail rows
  const rows: Array<[string, string]> = [
    ["Employee", entry.employeeName],
    ["Shop", entry.shopName || "—"],
    ["Date", entry.date],
  ];
  if (entry.balanceAfter != null) {
    rows.push(["Balance after", `SAR ${fmt(entry.balanceAfter)}${entry.balanceAfter > 0 ? " Due" : entry.balanceAfter < 0 ? " Advance" : ""}`]);
  }
  if (entry.notes) rows.push(["Notes", entry.notes]);

  let y = cardY + 360;
  ctx.textAlign = "left";
  for (const [label, value] of rows) {
    ctx.fillStyle = "#64748B";
    ctx.font = "500 26px Inter, system-ui, sans-serif";
    ctx.fillText(label, cardX + 60, y);
    ctx.fillStyle = "#F1F5F9";
    ctx.font = "600 30px Inter, system-ui, sans-serif";
    ctx.textAlign = "right";
    wrapTextRight(ctx, value, cardX + cardW - 60, y, cardW - 280, 36);
    ctx.textAlign = "left";
    y += 64;
  }

  // Footer
  ctx.textAlign = "center";
  ctx.fillStyle = accentSoft;
  ctx.font = "700 28px Inter, system-ui, sans-serif";
  ctx.fillText(isGiven ? "Cash Out · From Company" : "Cash In · To Company", W / 2, H - 130);

  ctx.fillStyle = "#475569";
  ctx.font = "500 22px Inter, system-ui, sans-serif";
  ctx.fillText("Auto-generated by " + COMPANY + " ERP", W / 2, H - 80);

  return await new Promise<Blob>((res) => canvas.toBlob((b) => res(b!), "image/png", 0.95));
}

function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + w, y, x + w, y + h, r);
  ctx.arcTo(x + w, y + h, x, y + h, r);
  ctx.arcTo(x, y + h, x, y, r);
  ctx.arcTo(x, y, x + w, y, r);
  ctx.closePath();
}

function wrapTextRight(
  ctx: CanvasRenderingContext2D,
  text: string,
  x: number,
  y: number,
  maxW: number,
  lh: number,
) {
  const words = text.split(" ");
  let line = "";
  const lines: string[] = [];
  for (const w of words) {
    const test = line ? line + " " + w : w;
    if (ctx.measureText(test).width > maxW && line) {
      lines.push(line);
      line = w;
    } else line = test;
  }
  if (line) lines.push(line);
  const max = Math.min(lines.length, 2);
  for (let i = 0; i < max; i++) {
    ctx.fillText(lines[i] + (i === 1 && lines.length > 2 ? "…" : ""), x, y + i * lh);
  }
}

export async function shareEmployeeEntry(entry: Entry) {
  const blob = await buildEmployeeShareImage(entry);
  const file = new File([blob], `employee-${entry.employeeName.replace(/\s+/g, "-")}.png`, { type: "image/png" });
  const navAny = navigator as any;
  if (navAny.canShare && navAny.canShare({ files: [file] })) {
    try {
      await navAny.share({
        files: [file],
        title: `${entry.employeeName} — ${entry.entryType === "given" ? "Money Given" : "Money Received"}`,
        text: `${COMPANY} · ${entry.entryType === "given" ? "Given" : "Received"} SAR ${fmt(entry.amount)}`,
      });
      return;
    } catch {
      /* fall through */
    }
  }
  // Fallback — download image and open WhatsApp web with text
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = file.name;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
  const text = encodeURIComponent(
    `${COMPANY}\n${entry.entryType === "given" ? "Money Given to" : "Money Received from"} ${entry.employeeName}\nAmount: SAR ${fmt(entry.amount)}\nDate: ${entry.date}${entry.notes ? "\nNotes: " + entry.notes : ""}`,
  );
  window.open(`https://wa.me/?text=${text}`, "_blank");
}
