/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWebsiteBannersRouteImport } from './routes/_app/website-banners'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppSummaryRouteImport } from './routes/_app/summary'
import { Route as AppStoreAdminRouteImport } from './routes/_app/store-admin'
import { Route as AppShopRouteImport } from './routes/_app/shop'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSalesReturnRouteImport } from './routes/_app/sales-return'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPushTestRouteImport } from './routes/_app/push-test'
import { Route as AppProfitSummaryRouteImport } from './routes/_app/profit-summary'
import { Route as AppPriceCompareRouteImport } from './routes/_app/price-compare'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppMyExpensesRouteImport } from './routes/_app/my-expenses'
import { Route as AppMonthlySnapshotRouteImport } from './routes/_app/monthly-snapshot'
import { Route as AppMonthlyClosingRouteImport } from './routes/_app/monthly-closing'
import { Route as AppLowStockRouteImport } from './routes/_app/low-stock'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppFinanceWorkflowRouteImport } from './routes/_app/finance-workflow'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppDailyClosingRouteImport } from './routes/_app/daily-closing'
import { Route as AppCompanyTransactionsRouteImport } from './routes/_app/company-transactions'
import { Route as AppCashFlowRouteImport } from './routes/_app/cash-flow'
import { Route as AppCashCustodyRouteImport } from './routes/_app/cash-custody'
import { Route as AppBannerAdsRouteImport } from './routes/_app/banner-ads'
import { Route as AppBackupCenterRouteImport } from './routes/_app/backup-center'
import { Route as AppAiInsightsRouteImport } from './routes/_app/ai-insights'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppStockCountIndexRouteImport } from './routes/_app/stock-count.index'
import { Route as AppEmployeesIndexRouteImport } from './routes/_app/employees.index'
import { Route as ApiPublicSendTestPushRouteImport } from './routes/api/public/send-test-push'
import { Route as ApiPublicSendOrderPushRouteImport } from './routes/api/public/send-order-push'
import { Route as ApiPublicSendOrderEmailRouteImport } from './routes/api/public/send-order-email'
import { Route as ApiPublicSendAuditEmailRouteImport } from './routes/api/public/send-audit-email'
import { Route as AppStockCountSessionIdRouteImport } from './routes/_app/stock-count.$sessionId'
import { Route as AppEmployeesExpensesRouteImport } from './routes/_app/employees.expenses'
import { Route as AppEmployeesEmployeeIdRouteImport } from './routes/_app/employees.$employeeId'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsiteBannersRoute = AppWebsiteBannersRouteImport.update({
  id: '/website-banners',
  path: '/website-banners',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSummaryRoute = AppSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreAdminRoute = AppStoreAdminRouteImport.update({
  id: '/store-admin',
  path: '/store-admin',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesReturnRoute = AppSalesReturnRouteImport.update({
  id: '/sales-return',
  path: '/sales-return',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPushTestRoute = AppPushTestRouteImport.update({
  id: '/push-test',
  path: '/push-test',
  getParentRoute: () => AppRoute,
} as any)
const AppProfitSummaryRoute = AppProfitSummaryRouteImport.update({
  id: '/profit-summary',
  path: '/profit-summary',
  getParentRoute: () => AppRoute,
} as any)
const AppPriceCompareRoute = AppPriceCompareRouteImport.update({
  id: '/price-compare',
  path: '/price-compare',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppMyExpensesRoute = AppMyExpensesRouteImport.update({
  id: '/my-expenses',
  path: '/my-expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppMonthlySnapshotRoute = AppMonthlySnapshotRouteImport.update({
  id: '/monthly-snapshot',
  path: '/monthly-snapshot',
  getParentRoute: () => AppRoute,
} as any)
const AppMonthlyClosingRoute = AppMonthlyClosingRouteImport.update({
  id: '/monthly-closing',
  path: '/monthly-closing',
  getParentRoute: () => AppRoute,
} as any)
const AppLowStockRoute = AppLowStockRouteImport.update({
  id: '/low-stock',
  path: '/low-stock',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceWorkflowRoute = AppFinanceWorkflowRouteImport.update({
  id: '/finance-workflow',
  path: '/finance-workflow',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDailyClosingRoute = AppDailyClosingRouteImport.update({
  id: '/daily-closing',
  path: '/daily-closing',
  getParentRoute: () => AppRoute,
} as any)
const AppCompanyTransactionsRoute = AppCompanyTransactionsRouteImport.update({
  id: '/company-transactions',
  path: '/company-transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppCashFlowRoute = AppCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => AppRoute,
} as any)
const AppCashCustodyRoute = AppCashCustodyRouteImport.update({
  id: '/cash-custody',
  path: '/cash-custody',
  getParentRoute: () => AppRoute,
} as any)
const AppBannerAdsRoute = AppBannerAdsRouteImport.update({
  id: '/banner-ads',
  path: '/banner-ads',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupCenterRoute = AppBackupCenterRouteImport.update({
  id: '/backup-center',
  path: '/backup-center',
  getParentRoute: () => AppRoute,
} as any)
const AppAiInsightsRoute = AppAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppStockCountIndexRoute = AppStockCountIndexRouteImport.update({
  id: '/stock-count/',
  path: '/stock-count/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicSendTestPushRoute = ApiPublicSendTestPushRouteImport.update({
  id: '/api/public/send-test-push',
  path: '/api/public/send-test-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendOrderPushRoute = ApiPublicSendOrderPushRouteImport.update({
  id: '/api/public/send-order-push',
  path: '/api/public/send-order-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendOrderEmailRoute = ApiPublicSendOrderEmailRouteImport.update({
  id: '/api/public/send-order-email',
  path: '/api/public/send-order-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendAuditEmailRoute = ApiPublicSendAuditEmailRouteImport.update({
  id: '/api/public/send-audit-email',
  path: '/api/public/send-audit-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStockCountSessionIdRoute = AppStockCountSessionIdRouteImport.update({
  id: '/stock-count/$sessionId',
  path: '/stock-count/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesExpensesRoute = AppEmployeesExpensesRouteImport.update({
  id: '/employees/expenses',
  path: '/employees/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesEmployeeIdRoute = AppEmployeesEmployeeIdRouteImport.update({
  id: '/employees/$employeeId',
  path: '/employees/$employeeId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/store': typeof StoreRoute
  '/activity': typeof AppActivityRoute
  '/ai-insights': typeof AppAiInsightsRoute
  '/backup-center': typeof AppBackupCenterRoute
  '/banner-ads': typeof AppBannerAdsRoute
  '/cash-custody': typeof AppCashCustodyRoute
  '/cash-flow': typeof AppCashFlowRoute
  '/company-transactions': typeof AppCompanyTransactionsRoute
  '/daily-closing': typeof AppDailyClosingRoute
  '/dashboard': typeof AppDashboardRoute
  '/finance-workflow': typeof AppFinanceWorkflowRoute
  '/help': typeof AppHelpRoute
  '/low-stock': typeof AppLowStockRoute
  '/monthly-closing': typeof AppMonthlyClosingRoute
  '/monthly-snapshot': typeof AppMonthlySnapshotRoute
  '/my-expenses': typeof AppMyExpensesRoute
  '/overview': typeof AppOverviewRoute
  '/price-compare': typeof AppPriceCompareRoute
  '/profit-summary': typeof AppProfitSummaryRoute
  '/push-test': typeof AppPushTestRoute
  '/reports': typeof AppReportsRoute
  '/sales-return': typeof AppSalesReturnRoute
  '/settings': typeof AppSettingsRoute
  '/shop': typeof AppShopRoute
  '/store-admin': typeof AppStoreAdminRoute
  '/summary': typeof AppSummaryRoute
  '/team': typeof AppTeamRoute
  '/website-banners': typeof AppWebsiteBannersRoute
  '/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/employees/expenses': typeof AppEmployeesExpensesRoute
  '/stock-count/$sessionId': typeof AppStockCountSessionIdRoute
  '/api/public/send-audit-email': typeof ApiPublicSendAuditEmailRoute
  '/api/public/send-order-email': typeof ApiPublicSendOrderEmailRoute
  '/api/public/send-order-push': typeof ApiPublicSendOrderPushRoute
  '/api/public/send-test-push': typeof ApiPublicSendTestPushRoute
  '/employees/': typeof AppEmployeesIndexRoute
  '/stock-count/': typeof AppStockCountIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/store': typeof StoreRoute
  '/activity': typeof AppActivityRoute
  '/ai-insights': typeof AppAiInsightsRoute
  '/backup-center': typeof AppBackupCenterRoute
  '/banner-ads': typeof AppBannerAdsRoute
  '/cash-custody': typeof AppCashCustodyRoute
  '/cash-flow': typeof AppCashFlowRoute
  '/company-transactions': typeof AppCompanyTransactionsRoute
  '/daily-closing': typeof AppDailyClosingRoute
  '/dashboard': typeof AppDashboardRoute
  '/finance-workflow': typeof AppFinanceWorkflowRoute
  '/help': typeof AppHelpRoute
  '/low-stock': typeof AppLowStockRoute
  '/monthly-closing': typeof AppMonthlyClosingRoute
  '/monthly-snapshot': typeof AppMonthlySnapshotRoute
  '/my-expenses': typeof AppMyExpensesRoute
  '/overview': typeof AppOverviewRoute
  '/price-compare': typeof AppPriceCompareRoute
  '/profit-summary': typeof AppProfitSummaryRoute
  '/push-test': typeof AppPushTestRoute
  '/reports': typeof AppReportsRoute
  '/sales-return': typeof AppSalesReturnRoute
  '/settings': typeof AppSettingsRoute
  '/shop': typeof AppShopRoute
  '/store-admin': typeof AppStoreAdminRoute
  '/summary': typeof AppSummaryRoute
  '/team': typeof AppTeamRoute
  '/website-banners': typeof AppWebsiteBannersRoute
  '/': typeof AppIndexRoute
  '/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/employees/expenses': typeof AppEmployeesExpensesRoute
  '/stock-count/$sessionId': typeof AppStockCountSessionIdRoute
  '/api/public/send-audit-email': typeof ApiPublicSendAuditEmailRoute
  '/api/public/send-order-email': typeof ApiPublicSendOrderEmailRoute
  '/api/public/send-order-push': typeof ApiPublicSendOrderPushRoute
  '/api/public/send-test-push': typeof ApiPublicSendTestPushRoute
  '/employees': typeof AppEmployeesIndexRoute
  '/stock-count': typeof AppStockCountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/store': typeof StoreRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/ai-insights': typeof AppAiInsightsRoute
  '/_app/backup-center': typeof AppBackupCenterRoute
  '/_app/banner-ads': typeof AppBannerAdsRoute
  '/_app/cash-custody': typeof AppCashCustodyRoute
  '/_app/cash-flow': typeof AppCashFlowRoute
  '/_app/company-transactions': typeof AppCompanyTransactionsRoute
  '/_app/daily-closing': typeof AppDailyClosingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/finance-workflow': typeof AppFinanceWorkflowRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/low-stock': typeof AppLowStockRoute
  '/_app/monthly-closing': typeof AppMonthlyClosingRoute
  '/_app/monthly-snapshot': typeof AppMonthlySnapshotRoute
  '/_app/my-expenses': typeof AppMyExpensesRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/price-compare': typeof AppPriceCompareRoute
  '/_app/profit-summary': typeof AppProfitSummaryRoute
  '/_app/push-test': typeof AppPushTestRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sales-return': typeof AppSalesReturnRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shop': typeof AppShopRoute
  '/_app/store-admin': typeof AppStoreAdminRoute
  '/_app/summary': typeof AppSummaryRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/website-banners': typeof AppWebsiteBannersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/_app/employees/expenses': typeof AppEmployeesExpensesRoute
  '/_app/stock-count/$sessionId': typeof AppStockCountSessionIdRoute
  '/api/public/send-audit-email': typeof ApiPublicSendAuditEmailRoute
  '/api/public/send-order-email': typeof ApiPublicSendOrderEmailRoute
  '/api/public/send-order-push': typeof ApiPublicSendOrderPushRoute
  '/api/public/send-test-push': typeof ApiPublicSendTestPushRoute
  '/_app/employees/': typeof AppEmployeesIndexRoute
  '/_app/stock-count/': typeof AppStockCountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/store'
    | '/activity'
    | '/ai-insights'
    | '/backup-center'
    | '/banner-ads'
    | '/cash-custody'
    | '/cash-flow'
    | '/company-transactions'
    | '/daily-closing'
    | '/dashboard'
    | '/finance-workflow'
    | '/help'
    | '/low-stock'
    | '/monthly-closing'
    | '/monthly-snapshot'
    | '/my-expenses'
    | '/overview'
    | '/price-compare'
    | '/profit-summary'
    | '/push-test'
    | '/reports'
    | '/sales-return'
    | '/settings'
    | '/shop'
    | '/store-admin'
    | '/summary'
    | '/team'
    | '/website-banners'
    | '/employees/$employeeId'
    | '/employees/expenses'
    | '/stock-count/$sessionId'
    | '/api/public/send-audit-email'
    | '/api/public/send-order-email'
    | '/api/public/send-order-push'
    | '/api/public/send-test-push'
    | '/employees/'
    | '/stock-count/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/store'
    | '/activity'
    | '/ai-insights'
    | '/backup-center'
    | '/banner-ads'
    | '/cash-custody'
    | '/cash-flow'
    | '/company-transactions'
    | '/daily-closing'
    | '/dashboard'
    | '/finance-workflow'
    | '/help'
    | '/low-stock'
    | '/monthly-closing'
    | '/monthly-snapshot'
    | '/my-expenses'
    | '/overview'
    | '/price-compare'
    | '/profit-summary'
    | '/push-test'
    | '/reports'
    | '/sales-return'
    | '/settings'
    | '/shop'
    | '/store-admin'
    | '/summary'
    | '/team'
    | '/website-banners'
    | '/'
    | '/employees/$employeeId'
    | '/employees/expenses'
    | '/stock-count/$sessionId'
    | '/api/public/send-audit-email'
    | '/api/public/send-order-email'
    | '/api/public/send-order-push'
    | '/api/public/send-test-push'
    | '/employees'
    | '/stock-count'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/store'
    | '/_app/activity'
    | '/_app/ai-insights'
    | '/_app/backup-center'
    | '/_app/banner-ads'
    | '/_app/cash-custody'
    | '/_app/cash-flow'
    | '/_app/company-transactions'
    | '/_app/daily-closing'
    | '/_app/dashboard'
    | '/_app/finance-workflow'
    | '/_app/help'
    | '/_app/low-stock'
    | '/_app/monthly-closing'
    | '/_app/monthly-snapshot'
    | '/_app/my-expenses'
    | '/_app/overview'
    | '/_app/price-compare'
    | '/_app/profit-summary'
    | '/_app/push-test'
    | '/_app/reports'
    | '/_app/sales-return'
    | '/_app/settings'
    | '/_app/shop'
    | '/_app/store-admin'
    | '/_app/summary'
    | '/_app/team'
    | '/_app/website-banners'
    | '/_app/'
    | '/_app/employees/$employeeId'
    | '/_app/employees/expenses'
    | '/_app/stock-count/$sessionId'
    | '/api/public/send-audit-email'
    | '/api/public/send-order-email'
    | '/api/public/send-order-push'
    | '/api/public/send-test-push'
    | '/_app/employees/'
    | '/_app/stock-count/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  StoreRoute: typeof StoreRoute
  ApiPublicSendAuditEmailRoute: typeof ApiPublicSendAuditEmailRoute
  ApiPublicSendOrderEmailRoute: typeof ApiPublicSendOrderEmailRoute
  ApiPublicSendOrderPushRoute: typeof ApiPublicSendOrderPushRoute
  ApiPublicSendTestPushRoute: typeof ApiPublicSendTestPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/website-banners': {
      id: '/_app/website-banners'
      path: '/website-banners'
      fullPath: '/website-banners'
      preLoaderRoute: typeof AppWebsiteBannersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/summary': {
      id: '/_app/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof AppSummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store-admin': {
      id: '/_app/store-admin'
      path: '/store-admin'
      fullPath: '/store-admin'
      preLoaderRoute: typeof AppStoreAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shop': {
      id: '/_app/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-return': {
      id: '/_app/sales-return'
      path: '/sales-return'
      fullPath: '/sales-return'
      preLoaderRoute: typeof AppSalesReturnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/push-test': {
      id: '/_app/push-test'
      path: '/push-test'
      fullPath: '/push-test'
      preLoaderRoute: typeof AppPushTestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profit-summary': {
      id: '/_app/profit-summary'
      path: '/profit-summary'
      fullPath: '/profit-summary'
      preLoaderRoute: typeof AppProfitSummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/price-compare': {
      id: '/_app/price-compare'
      path: '/price-compare'
      fullPath: '/price-compare'
      preLoaderRoute: typeof AppPriceCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-expenses': {
      id: '/_app/my-expenses'
      path: '/my-expenses'
      fullPath: '/my-expenses'
      preLoaderRoute: typeof AppMyExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monthly-snapshot': {
      id: '/_app/monthly-snapshot'
      path: '/monthly-snapshot'
      fullPath: '/monthly-snapshot'
      preLoaderRoute: typeof AppMonthlySnapshotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monthly-closing': {
      id: '/_app/monthly-closing'
      path: '/monthly-closing'
      fullPath: '/monthly-closing'
      preLoaderRoute: typeof AppMonthlyClosingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/low-stock': {
      id: '/_app/low-stock'
      path: '/low-stock'
      fullPath: '/low-stock'
      preLoaderRoute: typeof AppLowStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance-workflow': {
      id: '/_app/finance-workflow'
      path: '/finance-workflow'
      fullPath: '/finance-workflow'
      preLoaderRoute: typeof AppFinanceWorkflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daily-closing': {
      id: '/_app/daily-closing'
      path: '/daily-closing'
      fullPath: '/daily-closing'
      preLoaderRoute: typeof AppDailyClosingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/company-transactions': {
      id: '/_app/company-transactions'
      path: '/company-transactions'
      fullPath: '/company-transactions'
      preLoaderRoute: typeof AppCompanyTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-flow': {
      id: '/_app/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof AppCashFlowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-custody': {
      id: '/_app/cash-custody'
      path: '/cash-custody'
      fullPath: '/cash-custody'
      preLoaderRoute: typeof AppCashCustodyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/banner-ads': {
      id: '/_app/banner-ads'
      path: '/banner-ads'
      fullPath: '/banner-ads'
      preLoaderRoute: typeof AppBannerAdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backup-center': {
      id: '/_app/backup-center'
      path: '/backup-center'
      fullPath: '/backup-center'
      preLoaderRoute: typeof AppBackupCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-insights': {
      id: '/_app/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AppAiInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock-count/': {
      id: '/_app/stock-count/'
      path: '/stock-count'
      fullPath: '/stock-count/'
      preLoaderRoute: typeof AppStockCountIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/': {
      id: '/_app/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/send-test-push': {
      id: '/api/public/send-test-push'
      path: '/api/public/send-test-push'
      fullPath: '/api/public/send-test-push'
      preLoaderRoute: typeof ApiPublicSendTestPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-order-push': {
      id: '/api/public/send-order-push'
      path: '/api/public/send-order-push'
      fullPath: '/api/public/send-order-push'
      preLoaderRoute: typeof ApiPublicSendOrderPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-order-email': {
      id: '/api/public/send-order-email'
      path: '/api/public/send-order-email'
      fullPath: '/api/public/send-order-email'
      preLoaderRoute: typeof ApiPublicSendOrderEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-audit-email': {
      id: '/api/public/send-audit-email'
      path: '/api/public/send-audit-email'
      fullPath: '/api/public/send-audit-email'
      preLoaderRoute: typeof ApiPublicSendAuditEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/stock-count/$sessionId': {
      id: '/_app/stock-count/$sessionId'
      path: '/stock-count/$sessionId'
      fullPath: '/stock-count/$sessionId'
      preLoaderRoute: typeof AppStockCountSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/expenses': {
      id: '/_app/employees/expenses'
      path: '/employees/expenses'
      fullPath: '/employees/expenses'
      preLoaderRoute: typeof AppEmployeesExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/$employeeId': {
      id: '/_app/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof AppEmployeesEmployeeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAiInsightsRoute: typeof AppAiInsightsRoute
  AppBackupCenterRoute: typeof AppBackupCenterRoute
  AppBannerAdsRoute: typeof AppBannerAdsRoute
  AppCashCustodyRoute: typeof AppCashCustodyRoute
  AppCashFlowRoute: typeof AppCashFlowRoute
  AppCompanyTransactionsRoute: typeof AppCompanyTransactionsRoute
  AppDailyClosingRoute: typeof AppDailyClosingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceWorkflowRoute: typeof AppFinanceWorkflowRoute
  AppHelpRoute: typeof AppHelpRoute
  AppLowStockRoute: typeof AppLowStockRoute
  AppMonthlyClosingRoute: typeof AppMonthlyClosingRoute
  AppMonthlySnapshotRoute: typeof AppMonthlySnapshotRoute
  AppMyExpensesRoute: typeof AppMyExpensesRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppPriceCompareRoute: typeof AppPriceCompareRoute
  AppProfitSummaryRoute: typeof AppProfitSummaryRoute
  AppPushTestRoute: typeof AppPushTestRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesReturnRoute: typeof AppSalesReturnRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShopRoute: typeof AppShopRoute
  AppStoreAdminRoute: typeof AppStoreAdminRoute
  AppSummaryRoute: typeof AppSummaryRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWebsiteBannersRoute: typeof AppWebsiteBannersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEmployeesEmployeeIdRoute: typeof AppEmployeesEmployeeIdRoute
  AppEmployeesExpensesRoute: typeof AppEmployeesExpensesRoute
  AppStockCountSessionIdRoute: typeof AppStockCountSessionIdRoute
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
  AppStockCountIndexRoute: typeof AppStockCountIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAiInsightsRoute: AppAiInsightsRoute,
  AppBackupCenterRoute: AppBackupCenterRoute,
  AppBannerAdsRoute: AppBannerAdsRoute,
  AppCashCustodyRoute: AppCashCustodyRoute,
  AppCashFlowRoute: AppCashFlowRoute,
  AppCompanyTransactionsRoute: AppCompanyTransactionsRoute,
  AppDailyClosingRoute: AppDailyClosingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceWorkflowRoute: AppFinanceWorkflowRoute,
  AppHelpRoute: AppHelpRoute,
  AppLowStockRoute: AppLowStockRoute,
  AppMonthlyClosingRoute: AppMonthlyClosingRoute,
  AppMonthlySnapshotRoute: AppMonthlySnapshotRoute,
  AppMyExpensesRoute: AppMyExpensesRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppPriceCompareRoute: AppPriceCompareRoute,
  AppProfitSummaryRoute: AppProfitSummaryRoute,
  AppPushTestRoute: AppPushTestRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesReturnRoute: AppSalesReturnRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShopRoute: AppShopRoute,
  AppStoreAdminRoute: AppStoreAdminRoute,
  AppSummaryRoute: AppSummaryRoute,
  AppTeamRoute: AppTeamRoute,
  AppWebsiteBannersRoute: AppWebsiteBannersRoute,
  AppIndexRoute: AppIndexRoute,
  AppEmployeesEmployeeIdRoute: AppEmployeesEmployeeIdRoute,
  AppEmployeesExpensesRoute: AppEmployeesExpensesRoute,
  AppStockCountSessionIdRoute: AppStockCountSessionIdRoute,
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
  AppStockCountIndexRoute: AppStockCountIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  StoreRoute: StoreRoute,
  ApiPublicSendAuditEmailRoute: ApiPublicSendAuditEmailRoute,
  ApiPublicSendOrderEmailRoute: ApiPublicSendOrderEmailRoute,
  ApiPublicSendOrderPushRoute: ApiPublicSendOrderPushRoute,
  ApiPublicSendTestPushRoute: ApiPublicSendTestPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
